### ISSUE TITLE
Allow for basic airflow deployment alerts based on our metrics

### ISSUE THREAD

**Issue by schnie** [astronomerio/astronomer-ee#135]
We have a lot of data in Prometheus now, and we can start to trigger some alerts from some generic queries, and send them through to Alertmanager.

Alertmanager can aggregate and trigger a webhook to Houston where we can finally send out email alerts.

At a minimum, users should be able to add a comma separated list of email addresses that we should forward these alerts to.

**Comment by pcmaffey** [comment]
Do we want to implement this as a role?

**Comment by schnie** [comment]
@cwurtz can users have multiple roles assigned? I think right now we kind of treat them as a hierarchy right? I'm not sure if it fits that model, but could if users can have multiple roles. 

There's also the use-case where they want to add a slack channel email or something that doesn't really belong to a user account, so we may want to keep this separate. What you think @cwurtz?

**Comment by cwurtz** [comment]
Right now when a user is added to a workspace, they are added to the workspace group as an admin.  We don't explicitly add users to deployments, they just get access because they are an admin.

Once we have full group support for workspaces and deployment, we could add support for selecting groups which should receive notifications.  Maybe a separate list for workspace groups and deployment groups. Then add support for each user to select their notification preferences.

**Comment by ryw** [comment]
shipped in 0.7
