### ISSUE TITLE
Specify postgres to connect to internal cluster, not the nodeport cluster

### ISSUE THREAD

**Issue by vparekh94** [astronomerio/astronomer-ee#63]
The postgres database documentation from the default postgresql helm chart assumes a nodeport connection not to the internal cluster.

This causes some funny business to go on with the registry - the deployment resets to cli-1 when houston crashes.

**Comment by vparekh94** [comment]
@cwurtz @schnie where in the docs should this go?

**Comment by cwurtz** [comment]
Currently, the `cli-#` isn't tied to Houston.  It's tied to the latest tagged image in the registry.  If it's reset to 1 it's because the registry crashed/restarted.  Greg created an issue in the helm repo for adding a stateful set to the registry https://github.com/astronomerio/helm.astronomer.io/issues/9

**Comment by vparekh94** [comment]
Looks like this can be closed with the above merge.
